# -*- coding: utf-8 -*-
"""DictionariesLK

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JUXS-O6wm_h5Q9cXr7h_Wj3sqfX9lr1R
"""

persons = {'Danny': 'New York', 'Ben': 'New Jersey', 'Bob': 'Chicago', 'Tom': 'Houston', 'Nancy': 'Chicago'}
List = []
for key in persons:
  if persons[key] == 'Chicago':
      List.append(key)
print(List)

# We can also do:

persons = [key for key in persons if persons[key] == 'Chicago']
print(persons)

original = {'Math': 'Alice', 'Science': 'Bob'}
new_original = {}
for key,value in original.items():
  new_original[value] = key
print(new_original)

employes = {'Alice': {'age': 25, 'department': 'Sales'}, 'Bob': {'age': 30, 'department': 'Marketing'}, 'Charlie': {'age': 28, 'department': 'Sales'}}
new_Dict = {}
for key,value in employes.items():
  for k,val in employes[key].items():
    if val == 'Sales':
      new_Dict[key] = value
print(new_Dict)

dict1 = {'a': 10, 'b': 20, 'c': 30}
dict2 = {'b': 15, 'c': 5, 'd': 50}

def combine_and_sum(dict1, dict2):
    result = dict1.copy()
    for key, value in dict2.items():
        if key in result:
            result[key] += value
        else:
            result[key] = value
    return result

combine_and_sum(dict1,dict2)

def main_menu():
  print('''Birthday Manager:
  1. Add a Birthday
  2. View a Birthday
  3. Display all Birthdays
  4. Exit
   ''')
  i = 1
  Birthday_list = {}
  while i != 0:
    choice = int(input('Enter your choice: '))
    print()
    if choice == 1:
      name = input("Enter Friend's name: ")
      birthday = input("Enter Birthday (e.g., YYYY-MM-DD): ")
      Birthday_list[name] = birthday
      print(f"{name}'s bithday has been added!\n")
    elif choice == 2:
      name1 = input("Enter the name of the friend whose birthday you want to view: ")
      for k,val in Birthday_list.items():
        if name1 == k:
          print(f"{name1}'s birthday is on {val}.\n")
    elif choice == 3:
      print("Friend's Birthdays: ")
      for key,value in Birthday_list.items():
        print(f"{key}: {value}")
      print()
    else:
      print('Goodbye!')
      i = 0

main_menu()