# -*- coding: utf-8 -*-
"""SetsLK_CH09

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u-mvK_JxwYOvb6zTOez_ksIG8yqckoPW
"""

baseball = set(['Jodi', 'Carmen', 'Aida', 'Alicia'])
basketball = set(['Eva', 'Carmen', 'Alicia', 'Sarah'])
print("The following students are on the baseball team: ")
for i in baseball:
  print(i)
print()
print("The following students are on the basketball team: ")
for j in basketball:
  print(j)
print()
print("The following students play both baseball and basketball: ")
for i in baseball:
  for j in basketball:
    if i == j:
      print(i)
print()
new_set = set(list(baseball)+list(basketball))
print("The following students play either baseball or basketball: ")
for i in new_set:
  print(i)
print()
new_set1 = baseball-basketball
print("The following students play baseball, but not basketball: ")
for i in new_set1:
  print(i)
print()
new_set2 = basketball-baseball
print("The following students play basketball, but not baseball: ")
for i in new_set2:
  print(i)
print()
new_set3 = set(list(new_set1)+list(new_set2))
print("The following students play one sport, but not both: ")
for i in new_set3:
  print(i)